version: "3"
services:
 mqtt:
      image: toke/mosquitto
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
      restart: unless-stopped


#image classify subscriber

 split1subscriberdataset:
      build: ../subscriber
      image: split1subscriberdataset
      depends_on:
        - mqtt #ook eens testen zonder





