# FROM rpibaseimage2
# FROM nano-cv-tf-mqtt
FROM cloudbaseimage
# RUN pip install pytz
# RUN pip install --upgrade tensorflow-hub
ADD video_15-37.mp4 /
ADD video_15-37.xml /
ADD CloudOnlyPublisher.py /
CMD ["./CloudOnlyPublisher.py"]